insert into caracteristica(nome,descricao) values('eletronicos', 'produtos eletronicos')
insert into caracteristica(nome,descricao) values('marca', 'multilaser')
insert into caracteristica(nome,descricao) values('cor', 'preto')
insert into caracteristica(nome,descricao) values('peso', 'pesado')
insert into caracteristica(nome,descricao) values('tamanho', 'grande')